name: app
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
# You can override these in the flutter build command.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  image_cropper: ^1.4.1
  email_validator: ^2.0.1
  country_picker: ^2.0.11
  cloud_firestore: ^4.0.0  # Add the latest version of Firestore
  firebase_core: ^2.0.0

  # Adds Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.6
  flappy_search_bar_ns: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package for good coding practices
  flutter_lints: ^3.0.0
  image_picker: ^1.1.2

flutter:

  # Includes the Material Icons font
  uses-material-design: true

  # Adds image assets
  assets:
    - images/

# Fonts can be added by uncommenting and modifying the following section:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
